use_frameworks!

target 'NetworkServerKit_Example' do
  
	pod 'WBNetworkServerKit', '~> 0.2.5'
#pod 'WBNetworkServerKit', :path => '..'

  target 'NetworkServerKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
